import Link from 'next/link'
import { requireAdmin } from '@/lib/session'
import { getDashboardData } from '@/lib/data'
import { addSnapshotAction, deleteIssueAction, deleteTaskAction, logoutAction, saveIssueAction, savePhaseAction, saveProjectAction, saveTaskAction } from './actions'

function d(v?:string|null){return v??''}
export const dynamic='force-dynamic'
export default async function Admin({searchParams}:{searchParams:Promise<{saved?:string}>}){
  await requireAdmin(); const data=await getDashboardData(); const q=await searchParams; const p=data.project
  return <main className="admin-shell"><header className="admin-top"><div><span className="brand-mark">P</span><div><h1>Administração do cronograma</h1><small>{p.name} · {data.tasks.length} linhas</small></div></div><div className="admin-actions"><Link className="btn secondary" href="/">Ver painel público</Link><form action={logoutAction}><button className="btn secondary">Sair</button></form></div></header>
    {q.saved&&<p className="saved">Alteração salva no banco.</p>}
    <section className="admin-grid"><article className="admin-panel"><h2>Dados da obra</h2><form action={saveProjectAction} className="admin-form"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="slug" value={p.slug}/>
      <label className="full">NOME DA OBRA<input name="name" defaultValue={p.name} required/></label><label>CÓDIGO<input name="code" defaultValue={p.code}/></label><label>CLIENTE<input name="client" defaultValue={p.client}/></label><label className="full">LOCAL<input name="location" defaultValue={p.location}/></label>
      <label>INÍCIO<input name="start_date" type="date" defaultValue={p.start_date} required/></label><label>FIM<input name="end_date" type="date" defaultValue={p.end_date} required/></label><label>LINHA DE BASE<input name="baseline_end_date" type="date" defaultValue={d(p.baseline_end_date)}/></label><label>AVANÇO GERAL %<input name="progress" type="number" min="0" max="100" step="0.1" defaultValue={p.progress}/></label>
      <label>STATUS<input name="status" defaultValue={p.status}/></label><label>TIPO<select name="data_status" defaultValue={p.data_status}><option value="modelo_inicial">Modelo para adaptação</option><option value="obra_real">Obra real</option></select></label><label className="full">FONTE DE REFERÊNCIA<input name="reference_source" defaultValue={d(p.reference_source)}/></label><div className="full"><button className="btn">Salvar dados da obra</button></div></form></article>
      <article className="admin-panel"><h2>Registrar medição / Curva S</h2><form action={addSnapshotAction} className="admin-form"><input type="hidden" name="project_id" value={p.id}/><label>DATA<input name="snapshot_date" type="date" required/></label><label>REAL %<input name="actual_progress" type="number" min="0" max="100" step="0.1" required/></label><label>PLANEJADO %<input name="planned_progress" type="number" min="0" max="100" step="0.1" required/></label><label className="full">OBSERVAÇÃO<input name="note" placeholder="Ex.: medição semanal"/></label><div className="full"><button className="btn">Salvar medição</button></div></form><p className="muted">O gráfico público usa o planejamento das atividades e mostra as medições reais que você registrar aqui.</p></article></section>

    <div className="admin-section-head"><div><span className="eyebrow">ESTRUTURA</span><h2>Frentes principais</h2></div></div><section className="admin-list">{data.phases.map(ph=><details className="admin-task" key={ph.id}><summary><b>{ph.name}</b><span>{ph.progress}% · {ph.planned_start} → {ph.planned_end}</span></summary><form action={savePhaseAction} className="admin-form"><input type="hidden" name="id" value={ph.id}/><input type="hidden" name="project_id" value={ph.project_id}/><input type="hidden" name="source_uid" value={ph.source_uid??''}/><label className="full">NOME<input name="name" defaultValue={ph.name} required/></label><label>ORDEM<input name="sort_order" type="number" defaultValue={ph.sort_order}/></label><label>RESPONSÁVEL<input name="responsible" defaultValue={ph.responsible}/></label><label>INÍCIO<input name="planned_start" type="date" defaultValue={ph.planned_start}/></label><label>FIM<input name="planned_end" type="date" defaultValue={ph.planned_end}/></label><label>AVANÇO %<input name="progress" type="number" min="0" max="100" step="0.1" defaultValue={ph.progress}/></label><label>STATUS<input name="status" defaultValue={ph.status}/></label><label className="full">DESCRIÇÃO<textarea name="description" defaultValue={d(ph.description)} rows={2}/></label><div className="full"><button className="btn">Salvar frente</button></div></form></details>)}</section>

    <div className="admin-section-head"><div><span className="eyebrow">CRONOGRAMA</span><h2>Atividades</h2></div><span className="muted">Abra uma linha para editar.</span></div>
    <section className="admin-list"><details className="admin-task"><summary><b>＋ Nova atividade</b><span>Adicionar linha ao cronograma</span></summary><form action={saveTaskAction} className="admin-form"><input type="hidden" name="project_id" value={p.id}/><label>FRENTE<select name="phase_id" defaultValue=""><option value="">Sem frente</option>{data.phases.map(ph=><option key={ph.id} value={ph.id}>{ph.name}</option>)}</select></label><label>ORDEM<input name="sort_order" type="number" defaultValue={data.tasks.length+1}/></label><label className="full">ATIVIDADE<input name="name" required/></label><label>INÍCIO<input name="planned_start" type="date" required/></label><label>FIM<input name="planned_end" type="date" required/></label><label>AVANÇO %<input name="progress" type="number" min="0" max="100" defaultValue="0"/></label><label>STATUS<input name="status" defaultValue="Planejado"/></label><label>RESPONSÁVEL<input name="responsible" defaultValue="A definir"/></label><label>PREDECESSORA<input name="predecessor_text" placeholder="Ex.: 12 ou 12SS"/></label><label>NÍVEL<input name="outline_level" type="number" defaultValue="3"/></label><label>WBS<input name="wbs"/></label><label>INÍCIO REAL<input name="actual_start" type="date"/></label><label>FIM REAL<input name="actual_end" type="date"/></label><label className="full">NOTAS<textarea name="notes" rows={2}/></label><div className="checks full"><label><input name="critical" type="checkbox"/> Crítica</label><label><input name="is_milestone" type="checkbox"/> Marco</label><label><input name="is_summary" type="checkbox"/> Resumo</label></div><div className="full"><button className="btn">Adicionar atividade</button></div></form></details>
      {data.tasks.map(t=><details className="admin-task" key={t.id}><summary><b>{t.source_id?`${t.source_id}. `:''}{t.name}</b><span>{t.progress}% · {t.planned_start} → {t.planned_end}</span></summary><form action={saveTaskAction} className="admin-form"><input type="hidden" name="id" value={t.id}/><input type="hidden" name="project_id" value={t.project_id}/><input type="hidden" name="source_id" value={t.source_id??''}/><input type="hidden" name="source_uid" value={t.source_uid??''}/><input type="hidden" name="parent_source_uid" value={t.parent_source_uid??''}/>
        <label>FRENTE<select name="phase_id" defaultValue={t.phase_id??''}><option value="">Sem frente</option>{data.phases.map(ph=><option key={ph.id} value={ph.id}>{ph.name}</option>)}</select></label><label>ORDEM<input name="sort_order" type="number" defaultValue={t.sort_order}/></label><label className="full">ATIVIDADE<input name="name" defaultValue={t.name} required/></label><label>INÍCIO<input name="planned_start" type="date" defaultValue={t.planned_start}/></label><label>FIM<input name="planned_end" type="date" defaultValue={t.planned_end}/></label><label>AVANÇO %<input name="progress" type="number" min="0" max="100" step="0.1" defaultValue={t.progress}/></label><label>STATUS<input name="status" defaultValue={t.status}/></label><label>RESPONSÁVEL<input name="responsible" defaultValue={t.responsible}/></label><label>PREDECESSORA<input name="predecessor_text" defaultValue={d(t.predecessor_text)}/></label><label>NÍVEL<input name="outline_level" type="number" defaultValue={t.outline_level}/></label><label>WBS<input name="wbs" defaultValue={t.wbs}/></label><label>INÍCIO REAL<input name="actual_start" type="date" defaultValue={d(t.actual_start)}/></label><label>FIM REAL<input name="actual_end" type="date" defaultValue={d(t.actual_end)}/></label><label className="full">NOTAS<textarea name="notes" defaultValue={d(t.notes)} rows={2}/></label><div className="checks full"><label><input name="critical" type="checkbox" defaultChecked={t.critical}/> Crítica</label><label><input name="is_milestone" type="checkbox" defaultChecked={t.is_milestone}/> Marco</label><label><input name="is_summary" type="checkbox" defaultChecked={t.is_summary}/> Resumo</label></div><div className="full"><button className="btn">Salvar atividade</button></div></form><form action={deleteTaskAction} className="admin-form"><input type="hidden" name="id" value={t.id}/><div className="danger-zone"><button className="btn danger">Excluir atividade</button></div></form></details>)}</section>

    <div className="admin-section-head"><div><span className="eyebrow">GESTÃO</span><h2>Pendências</h2></div></div><section className="admin-list"><details className="admin-task"><summary><b>＋ Nova pendência</b><span>Criar item de acompanhamento</span></summary><form action={saveIssueAction} className="admin-form"><input type="hidden" name="project_id" value={p.id}/><label className="full">TÍTULO<input name="title" required/></label><label>CATEGORIA<input name="category" defaultValue="Geral"/></label><label>PRIORIDADE<select name="priority" defaultValue="media"><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></label><label>STATUS<input name="status" defaultValue="Aberta"/></label><label>RESPONSÁVEL<input name="owner"/></label><label>PRAZO<input name="due_date" type="date"/></label><label className="full">NOTAS<textarea name="notes" rows={2}/></label><div className="full"><button className="btn">Adicionar pendência</button></div></form></details>{data.issues.map(i=><details className="admin-task" key={i.id}><summary><b>{i.title}</b><span>{i.priority} · {i.status}</span></summary><form action={saveIssueAction} className="admin-form"><input type="hidden" name="id" value={i.id}/><input type="hidden" name="project_id" value={i.project_id}/><label className="full">TÍTULO<input name="title" defaultValue={i.title}/></label><label>CATEGORIA<input name="category" defaultValue={i.category}/></label><label>PRIORIDADE<select name="priority" defaultValue={i.priority}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></label><label>STATUS<input name="status" defaultValue={i.status}/></label><label>RESPONSÁVEL<input name="owner" defaultValue={i.owner}/></label><label>PRAZO<input name="due_date" type="date" defaultValue={d(i.due_date)}/></label><label className="full">NOTAS<textarea name="notes" defaultValue={d(i.notes)} rows={2}/></label><div className="full"><button className="btn">Salvar pendência</button></div></form><form action={deleteIssueAction} className="admin-form"><input type="hidden" name="id" value={i.id}/><div className="danger-zone"><button className="btn danger">Excluir pendência</button></div></form></details>)}</section>
  </main>
}
